[package]
name = "hello_macro_derive"
version = "0.1.0"
edition = "2024"

[lib]
# if not used, report:  use of unresolved module or unlinked crate `proc_macro
proc-macro = true

[dependencies]
syn = "0.14.4"
quote = "0.6.3"